### ISSUE TITLE
documentation - broken link for metadata & schemas

### ISSUE THREAD

**Issue by feroda** [italia/daf-docs#35]
I was studying for the hackathon.
Broken link on page Concepts https://daf-docs.readthedocs.io/en/latest/concepts/index.html

The first "Metadata & Schemas" refers to the INEXISTENT
https://daf-docs.readthedocs.io/en/latest/concepts/dataset-metadata-schemas.html

whereas the second to the EXISTENT
https://daf-docs.readthedocs.io/en/latest/concepts/dataset-metadata-schemas/index.html

A fix will be useful for the hackathon

**Comment by ruphy** [comment]
thanks a lot for the report! as you can see from the current commits we are working on this as we speak ;-)
anyways, will push a fix now ;-)

**Comment by feroda** [comment]
I forked and was creating a PR, you have been faster! ;-)
Thanks

**Comment by ruphy** [comment]
PRs are of course always super welcome! :-)
