### ISSUE TITLE
Virtual Machine download link not working

### ISSUE THREAD

**Issue by Lytrix** [italia/daf-docs#48]
I wanted to download the virtual machine example to check out the system, only the link https://drive.google.com/file/d/0Bzp1CVf8pK-yQWtSb1RKanBWNm8/view  is not working which is described here: https://github.com/italia/daf-docs/blob/master/installation/index.rst

**Comment by altroisi** [comment]
Move the VM image on another account with available space

**Comment by ruphy** [comment]
@altroisi just making sure, as it is not clear from your text 🙂 :
are you taking care of this or are you asking @fabiofumarola to do it?

**Comment by altroisi** [comment]
Sorry @ruphy, the second one. I think it's better to put the image on an "official" drive rather than a private one. In the meantime I retrieved the file, I ask to you or to @fabiofumarola where to put it

**Comment by ruphy** [comment]
OK, I think that we can even upload it on developers.italia.it, or on GitHub? Does it change frequently?

**Comment by giux78** [comment]
We are uploading the VM somewhere tomorrow.

**Comment by Lytrix** [comment]
Great! Want to have a look if it would also fits our data analist team at the city of amsterdam. We are also building a lot of reusable building blocks here but are just starting on the analysis blocks if you guys are interested: https://www.github.com/amsterdam for example an updated ckan engine.

**Comment by giux78** [comment]
Sure we hope to be able to upload everything today.  It will be useful to share code and knowledge. Keep in touch @Lytrix . Thanks!!!

**Comment by ruphy** [comment]
@Lytrix Cool! I think you can have an early preview of the dataportal here: https://dataportal.daf.teamdigitale.it/
Also, we have made a short video (alpha version, excuse the quality) with English subtitles: https://www.youtube.com/watch?v=X2Sg-KauY6I

Feel free to also poke us on [our slack](https://slack.developers.italia.it)!

**Comment by giux78** [comment]
here the link to the instructions to launch a local version of DAF. https://daf-docs.readthedocs.io/en/latest/installation/local/devVM.html

**Comment by ruphy** [comment]
@Lytrix so this is the new version of the VM 😉

**Comment by ruphy** [comment]
https://developers.italia.it/static/DAF-Ubuntu16-Docker-test.ova

**Comment by Lytrix** [comment]
@ruphy Thanks for getting the VM back up so quickly! I will spin it up to try to get some examples running with our data to pitch it to our data scientists and developers here.

**Comment by ruphy** [comment]
@Lytrix happy to help! We're currently working to make the development environment as easy and as light as possible for other people to extend. The infrastructure is complex due to the security and scalability requirements, but we're getting there. If you have any kind of feedback, don't hesitate to get involved!

**Comment by rbcb-dev** [comment]
@ruphy Hi, what is the status on DAF? We are also interested in this project. Do you have any news to install and try locally? The link to the VM is offline unfortunately.

**Comment by ruphy** [comment]
@rbcb-bedag DAF is dead, long live PDND: https://www.pagopa.it/it/prodotti-e-servizi/piattaforma-digitale-nazionale-dati

**Comment by ioggstream** [comment]
Archive the project please @Riccardo Iaconelli
***@***.***>

Il gio 5 mag 2022, 06:50 Riccardo Iaconelli ***@***.***> ha
scritto:
