### ISSUE TITLE
Nuovo tema: menu richiudibile

### ISSUE THREAD

**Issue by francescozaia** [italia/daf-docs#60]
Raffaele segnala che il menu a sinistra sul vecchio tema era _collassabile_, @pdavide se non erro si tratta solo di un'impostazione nel `conf.py` o sbaglio?

**Comment by pdavide** [comment]
Per avere i menu collassati basta inserire il seguente codice nel `conf.py`.
```
html_theme_options = {
    'collapse_navigation': True
}
```
Questa stessa configurazione è utilizzata per il [Piano Triennale](https://pianotriennale-ict.readthedocs.io/it/latest/) nel [file di configurazione](https://github.com/italia/pianotriennale-ict-doc/blob/master/conf.py#L98) presente nel suo repo.

**Comment by atorin** [comment]
@pdavide grazie dell'informazione, questa mi mancava! Pensavo fosse una questione di tema.

Se volete me ne posso occupare io.

**Comment by francescozaia** [comment]
vai @atorin l'oggetto `html_theme_options` c'è già, credo basti aggiungere la variabile [qui](https://github.com/italia/daf-docs/blob/master/conf.py#L125)

**Comment by atorin** [comment]
Sì certo, ho fatto così
